### ISSUE TITLE
Allow urls to open in mobile web browser

### ISSUE THREAD

**Issue by DK15** [ibhavikmakwana/itsallwidgets_podcast#1]
Currently, the social media links on Details screen of corresponding dev aren't tappable. Make the urls tappable and open them in mobile web browser.

![screen shot 2019-01-21 at 3 18 21 pm](https://user-images.githubusercontent.com/16548367/51466289-d3a75b00-1d8f-11e9-8775-17bb5cba2e5f.png)

@ibhavikmakwana I have fix for this and will open a pr soon.

**Comment by DK15** [comment]
PR link : https://github.com/ibhavikmakwana/itsallwidgets_podcast/pull/2

**Comment by ibhavikmakwana** [comment]
PR merged
Closing this issue.
